export default function TermsPage() {
  return (
    <main className="mx-auto w-full max-w-3xl px-6 py-16">
      <h1 className="text-2xl font-bold tracking-tight text-[var(--fg)]">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-[var(--fg-muted)]">
        Last updated: April 2026
      </p>

      <div className="mt-10 space-y-8 text-sm leading-relaxed text-[var(--fg-muted)]">
        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            1. Acceptance of Terms
          </h2>
          <p className="mt-2">
            By accessing or using Intrvw.ai ("the Service"), you agree to be
            bound by these Terms of Service. If you do not agree, do not use the
            Service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            2. Description of Service
          </h2>
          <p className="mt-2">
            Intrvw.ai is an AI-powered interview coaching platform. You upload
            your resume and job description, answer generated interview
            questions, and receive scored feedback. The Service uses artificial
            intelligence to generate questions, score answers, and produce model
            responses.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            3. Your Data
          </h2>
          <p className="mt-2">
            You retain ownership of all content you upload, including resumes,
            job descriptions, and spoken answers. We process your data solely to
            provide the Service. We do not sell your personal data to third
            parties.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            4. AI-Generated Content
          </h2>
          <p className="mt-2">
            Interview questions, scores, feedback, and model answers are
            generated by AI and are provided for practice and coaching purposes
            only. They do not constitute professional career advice. Scores are
            relative assessments and may not reflect actual interview
            performance.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            5. Acceptable Use
          </h2>
          <p className="mt-2">
            You agree not to: (a) use the Service for any unlawful purpose; (b)
            upload content that infringes on intellectual property rights; (c)
            attempt to reverse-engineer, exploit, or abuse the Service; (d)
            create multiple accounts to circumvent usage limits.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            6. Account Termination
          </h2>
          <p className="mt-2">
            We reserve the right to suspend or terminate accounts that violate
            these terms or abuse the Service. You may delete your account at any
            time by contacting support.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            7. Limitation of Liability
          </h2>
          <p className="mt-2">
            The Service is provided "as is" without warranties of any kind.
            Intrvw.ai is not liable for any damages arising from your use of the
            Service, including but not limited to interview outcomes,
            employment decisions, or data loss.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            8. Changes to Terms
          </h2>
          <p className="mt-2">
            We may update these terms at any time. Continued use of the Service
            after changes constitutes acceptance of the revised terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            9. Contact
          </h2>
          <p className="mt-2">
            Questions about these terms? Email us at{" "}
            <a
              href="mailto:support@intrvw.ai"
              className="text-[var(--accent)] hover:underline"
            >
              support@intrvw.ai
            </a>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
