export default function PrivacyPage() {
  return (
    <main className="mx-auto w-full max-w-3xl px-6 py-16">
      <h1 className="text-2xl font-bold tracking-tight text-[var(--fg)]">
        Privacy Policy
      </h1>
      <p className="mt-2 text-sm text-[var(--fg-muted)]">
        Last updated: April 2026
      </p>

      <div className="mt-10 space-y-8 text-sm leading-relaxed text-[var(--fg-muted)]">
        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            1. What We Collect
          </h2>
          <p className="mt-2">
            When you use Intrvw.ai, we collect: (a) your email address and name
            when you create an account; (b) resume text and job descriptions you
            upload; (c) your spoken answers (transcribed text — we do not store
            raw audio); (d) session scores and feedback generated by AI.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            2. How We Use Your Data
          </h2>
          <p className="mt-2">
            We use your data to: (a) generate tailored interview questions; (b)
            score your answers and produce personalized feedback; (c)
            personalize model answers using your background; (d) show you
            progress across sessions; (e) send transactional emails (account
            confirmation, referral invites).
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            3. Third-Party Services
          </h2>
          <p className="mt-2">
            We use the following third-party services to operate: (a){" "}
            <strong>Anthropic (Claude)</strong> — your resume text, job
            descriptions, and answer transcripts are sent to Anthropic's API to
            generate questions, scores, and feedback. Anthropic does not use
            this data for training. (b) <strong>Supabase</strong> — for
            authentication and database storage. (c){" "}
            <strong>Vercel</strong> — for hosting. (d){" "}
            <strong>Resend</strong> — for transactional emails.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            4. Data Storage and Security
          </h2>
          <p className="mt-2">
            Your data is stored in Supabase (PostgreSQL) with row-level
            security. Only you can access your sessions, questions, and
            responses. Data is encrypted in transit (TLS) and at rest. We do not
            store raw audio recordings.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            5. Data Sharing
          </h2>
          <p className="mt-2">
            We do not sell, rent, or share your personal data with third parties
            for marketing purposes. We only share data with the third-party
            services listed above, strictly to provide the Service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            6. Data Retention
          </h2>
          <p className="mt-2">
            Your data is retained as long as your account is active. You may
            request deletion of your account and all associated data at any time
            by contacting us. We will delete your data within 30 days of your
            request.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            7. Cookies
          </h2>
          <p className="mt-2">
            We use essential cookies for authentication (Supabase session
            cookies). We do not use tracking cookies, advertising cookies, or
            analytics cookies.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            8. Your Rights
          </h2>
          <p className="mt-2">
            You have the right to: (a) access your personal data; (b) correct
            inaccurate data; (c) request deletion of your data; (d) export your
            data. Contact us to exercise these rights.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[var(--fg)]">
            9. Contact
          </h2>
          <p className="mt-2">
            Privacy questions? Email us at{" "}
            <a
              href="mailto:privacy@intrvw.ai"
              className="text-[var(--accent)] hover:underline"
            >
              privacy@intrvw.ai
            </a>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
